# Generated by Django 3.2.5 on 2021-08-01 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('vacancy', models.PositiveIntegerField(default=0)),
                ('experience', models.CharField(blank=True, choices=[('', 'choose job experience'), ('0_1_yrs', '0 - 1 (yrs)'), ('1_2_yrs', '1 - 2 (yrs)'), ('1_3_yrs', '1 - 3 (yrs)'), ('2_3_yrs', '2 - 3 (yrs)'), ('3_gt_yrs', 'Above 3 (yrs)')], max_length=244, null=True, verbose_name='Experience (yrs)')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('saved', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.category')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
