# Generated by Django 3.2.5 on 2021-08-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210801_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_on',
            field=models.DateField(),
        ),
    ]
