# Generated by Django 3.2.5 on 2021-08-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
