# Generated by Django 3.2.5 on 2021-08-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, choices=[('', 'choose job experience'), ('0 - 1 (yrs)', '0 - 1 (yrs)'), ('1 - 2 (yrs)', '1 - 2 (yrs)'), ('1 - 3 (yrs)', '1 - 3 (yrs)'), ('2 - 3 (yrs)', '2 - 3 (yrs)'), ('Above 3 (yrs)', 'Above 3 (yrs)')], max_length=244, null=True, verbose_name='Experience (yrs)'),
        ),
    ]
