# Generated by Django 3.2.5 on 2021-08-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='advance_level_certificate',
            field=models.FileField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='collage_level_certificate',
            field=models.FileField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='high_level_certificate',
            field=models.FileField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='olevel_certificate',
            field=models.FileField(max_length=50, upload_to=''),
        ),
    ]
