# Generated by Django 3.2.5 on 2021-08-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210801_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='will_relocate',
        ),
    ]
