# Generated by Django 3.2 on 2021-05-25 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccancy', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=255)),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('dadeline', models.DateField()),
                ('available', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='Full Name')),
                ('gender', models.CharField(default='', max_length=255, verbose_name='Gender')),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=244)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portalapp.userrole', verbose_name='user role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('certificates', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('user_profile', models.CharField(max_length=50)),
                ('seeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portalapp.profile', verbose_name='Seeker')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portalapp.user', verbose_name='profile owner'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apply_at', models.DateTimeField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portalapp.job', verbose_name='Job applied')),
                ('seeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portalapp.user', verbose_name='seeker')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portalapp.applicationstatus', verbose_name='application status')),
            ],
        ),
        migrations.CreateModel(
            name='Job_wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.job', verbose_name='Job')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.user', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.user', verbose_name='commentor')),
                ('job_commented', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portalapp.job', verbose_name='Job commented')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(max_length=50)),
                ('address_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.user', verbose_name='Client | company')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.city', verbose_name='Region')),
            ],
        ),
    ]
