# Generated by Django 3.2.5 on 2021-08-01 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerJobApplication',
            fields=[
                ('seeker_application_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('job_status', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('seeker_email', models.EmailField(max_length=255)),
                ('seeker_phone', models.CharField(max_length=255)),
                ('job_provider', models.CharField(max_length=255)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('seeker_job_experience', models.CharField(max_length=255)),
                ('application_status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=255)),
                ('seeker_cv', models.FileField(upload_to='cvs')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Review Seeker applications',
            },
        ),
        migrations.CreateModel(
            name='SaveJob',
            fields=[
                ('savejob_id', models.AutoField(primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('seeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
