# Generated by Django 3.2.5 on 2021-08-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seekerjobapplication',
            options={'verbose_name_plural': 'Review Applications'},
        ),
    ]
