# Generated by Django 3.2 on 2021-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0002_rename_wishlist_wishlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentor',
            field=models.TextField(),
        ),
    ]
