# Generated by Django 3.2 on 2021-06-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0004_auto_20210606_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlisted',
            new_name='Wishlist',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='cv',
            new_name='cv_attachment',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='education',
            new_name='education_level',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='status',
            new_name='hire_status',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user_profile',
        ),
    ]
