# Generated by Django 3.2 on 2021-06-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0005_auto_20210606_1840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='SaveJob',
        ),
    ]
