# Generated by Django 3.2 on 2021-06-14 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0008_alter_savedjob_seeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapp.userrole', verbose_name='user role'),
        ),
    ]
